const assert = require('assert')
const { createTrace } = require('../lib/timing')

;(async () => {
  let time = 0; const logs = []
  const trace = createTrace({ now: () => time, sample: () => 1, emit: value => logs.push(value) })
  await trace.measure('identity', async () => { time += 30 })
  await trace.measure('rateLimit', async () => { time += 20 })
  await trace.measure('handler', async () => { time += 1100 })
  trace.finish({ action: 'venues.list', requestId: 'request_perf_1', payload: 'PRIVATE', openid: 'SECRET' })
  assert.equal(logs.length, 1)
  assert.equal(logs[0].totalMs, 1150)
  assert.equal(logs[0].identityMs, 30)
  assert.equal(logs[0].rateLimitMs, 20)
  assert.equal(logs[0].handlerMs, 1100)
  assert(!JSON.stringify(logs).includes('PRIVATE')); assert(!JSON.stringify(logs).includes('SECRET'))
  const failed = createTrace({ now: () => time, sample: () => 1, emit: value => logs.push(value) })
  await assert.rejects(() => failed.measure('rateLimit', async () => { time += 10; throw new Error('PRIVATE ERROR') }))
  failed.finish({ action: 'venues.get', requestId: 'request_perf_2', code: 'SERVICE_UNAVAILABLE' })
  assert.equal(logs.at(-1).rateLimitMs, 10)
  const quick = createTrace({ now: () => time, sample: () => 1, emit: value => logs.push(value) })
  quick.finish({ action: 'venues.get', requestId: 'request_perf_3' })
  assert.equal(logs.length, 2)
  const brokenLog = createTrace({ now: () => time, emit: () => { throw new Error('logger failed') } })
  assert.doesNotThrow(() => brokenLog.finish({ action: 'venues.get', requestId: 'request_perf_4', code: 'INTERNAL' }))
  console.log('cloud-stage-timing-tests-ok')
})().catch(error => { console.error(error); process.exitCode = 1 })
